export const COLLECTIONS = {
  BUSINESSES: 'businesses',
  USERS: 'users',
  CUSTOMERS: 'customers',
  PRODUCTS: 'products',
  CAMPAIGNS: 'campaigns',
  ORDERS: 'orders',
  APPOINTMENTS: 'appointments',
  MESSAGES: 'messages',
  CONVERSATIONS: 'conversations',
  CHAT_ASSIGNMENTS: 'chat_assignments',
  CHATBOT_FLOWS: 'chatbot_flows',
  CHAT_TEMPLATES: 'chat_templates',
  TEMPLATES: 'templates',
  QUICK_REPLIES: 'quick_replies',
  NOTES: 'notes',
  NOTIFICATIONS: 'notifications',
  SESSIONS: 'sessions',
  CHAT_SESSIONS: 'chat_sessions',
  SUBSCRIPTIONS: 'subscriptions',
  USAGE: 'usage',
  SUPPORT_TICKETS: 'support_tickets',
  FEEDBACKS: 'feedbacks',
};

export default COLLECTIONS;
