export const sampleChatbotFlows = [
  {
    trigger: 'hi',
    reply: 'Welcome! Reply with 1 to view products or 2 to book an appointment.',
    step: 'start',
    nextStep: 'main_menu',
    action: 'NONE',
  },
  {
    trigger: '1',
    reply: 'Sure, here are the products:',
    step: 'main_menu',
    nextStep: 'main_menu',
    action: 'SHOW_PRODUCTS',
  },
  {
    trigger: '2',
    reply: 'Please enter the product name you want to order.',
    step: 'main_menu',
    nextStep: 'select_product',
    action: 'NONE',
  },
  {
    trigger: '3',
    reply: 'Please send the preferred date and time for your appointment.',
    step: 'main_menu',
    nextStep: 'ask_appointment_details',
    action: 'NONE',
  },
  {
    trigger: '4',
    reply: 'Please enter your order ID to request a return.',
    step: 'main_menu',
    nextStep: 'ask_return_order_id',
    action: 'NONE',
  },
  {
    trigger: '5',
    reply: 'Please enter your order ID to cancel.',
    step: 'main_menu',
    nextStep: 'ask_cancel_order_id',
    action: 'NONE',
  },
  {
    trigger: '6',
    reply: 'Please enter your existing query ID or type Continue to create a new query.',
    step: 'main_menu',
    nextStep: 'ask_feedback_query',
    action: 'NONE',
  },
  {
    trigger: '7',
    reply: 'Please provide your order ID so we can assist you with support.',
    step: 'main_menu',
    nextStep: 'ask_support_order_id',
    action: 'NONE',
  },
  {
    trigger: '5pm',
    reply: 'Thanks! Your appointment request is being processed.',
    step: 'booking',
    nextStep: 'main_menu',
    action: 'BOOK_APPOINTMENT',
  },
  {
    trigger: 'my name is',
    reply: 'Great! What is your full name?',
    step: 'start',
    nextStep: 'collect_name',
    action: 'SAVE_NAME',
  },
];
