import ChatbotFlow from '../models/ChatbotFlow.js';

const SAMPLE_FLOWS = [
  {
    trigger: 'hi',
    step: 'start',
    reply: 'Welcome. What is your name?',
    nextStep: 'ask_name',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: '1',
    step: 'menu',
    reply: 'Here are our products',
    nextStep: 'menu',
    action: 'SHOW_PRODUCTS',
    isActive: true,
  },
  {
    trigger: '2',
    step: 'menu',
    reply: 'Enter product name',
    nextStep: 'select_product',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: '3',
    step: 'menu',
    reply: 'Please share appointment date and time. Example: tomorrow 5pm',
    nextStep: 'ask_appointment_details',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: '4',
    step: 'menu',
    reply: 'Please enter your order ID to request a return.',
    nextStep: 'ask_return_order_id',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: '5',
    step: 'menu',
    reply: 'Please enter your order ID to cancel.',
    nextStep: 'ask_cancel_order_id',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: '6',
    step: 'menu',
    reply: 'Please enter your existing query ID or type Continue to create a new query.',
    nextStep: 'ask_feedback_query',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: '7',
    step: 'menu',
    reply: 'Please provide your order ID so we can assist you with support.',
    nextStep: 'ask_support_order_id',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'ask_feedback_text',
    step: 'system',
    reply: 'Tell me your query, please.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'ask_support_feedback',
    step: 'system',
    reply: 'Please share your feedback and mention the product name.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'ask_return_reason',
    step: 'system',
    reply: 'Please share the return reason.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'ask_cancel_reason',
    step: 'system',
    reply: 'Please share the cancellation reason.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'yes',
    step: 'confirm_order',
    reply: 'Order placed successfully',
    nextStep: 'menu',
    action: 'CREATE_ORDER',
    isActive: true,
  },
  {
    trigger: 'menu',
    step: 'system',
    reply: 'Menu Options:\n1. View products\n2. Order product\n3. Appointment booking\n4. Return product\n5. Cancel product\n6. Feedback\n7. Support\n\nType your choice or go back to continue.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'ask_address',
    step: 'system',
    reply: 'Please share your delivery address.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'confirm_saved_address',
    step: 'system',
    reply: 'We found your saved address:\n{{address}}\n\nContinue with this address?\n1. Continue\n2. New address',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'ask_quantity',
    step: 'system',
    reply: 'Enter product quantity (numbers only).',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'ask_coupon',
    step: 'system',
    reply: 'If you have a gift coupon, enter it now. Otherwise type \"no\".',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'ask_order_product_name',
    step: 'system',
    reply: 'Please type the product name to place your order.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'appointment_prompt',
    step: 'system',
    reply: 'Please share appointment date and time. Example: tomorrow 5pm',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'invalid_menu_choice',
    step: 'system',
    reply: 'I did not understand that choice.\n1. View products\n2. Order product\n3. Appointment booking\n4. Return product\n5. Cancel product\n6. Feedback\n7. Support',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'ask_name_prompt',
    step: 'system',
    reply: 'Welcome. Please share your name to continue.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'ask_age_prompt',
    step: 'system',
    reply: 'Please share your age (1-120).',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'error_no_product_selected',
    step: 'system',
    reply: 'No product selected. Please select a product first.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'error_customer_not_found',
    step: 'system',
    reply: 'Customer not found.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'error_order_amount',
    step: 'system',
    reply: 'Unable to calculate order amount. Please reselect the product.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'payment_link_text',
    step: 'system',
    reply: 'Pay here: {{paymentLink}}',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'payment_link_pending',
    step: 'system',
    reply: 'Payment link is being generated. Please contact support if it is not received.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'order_created_online',
    step: 'system',
    reply: 'Order created successfully. Order ID: {{orderId}}\nAmount: Rs {{amount}}\nPayment method: Online Payment\n{{paymentText}}\nAfter successful payment, your order will be confirmed automatically.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'opening_online_payment',
    step: 'system',
    reply: 'Opening Razorpay secure checkout...',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'order_created_cod',
    step: 'system',
    reply: 'Order confirmed successfully. Order ID: {{orderId}}\nAmount: Rs {{amount}}\nPayment method: Cash on Delivery',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'ask_payment_order_id',
    step: 'system',
    reply: 'Please share a valid order ID to check payment status.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'error_invalid_order_id',
    step: 'system',
    reply: 'Invalid order ID. Please check and try again.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'order_cancelled_status',
    step: 'system',
    reply: 'Order {{orderId}} is cancelled.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'order_status_summary',
    step: 'system',
    reply: 'Order {{orderId}}\nPayment Status: {{paymentStatus}}\nOrder Status: {{orderStatus}}',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'order_cancel_success',
    step: 'system',
    reply: 'Order {{orderId}} cancelled successfully.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'error_cancel_order',
    step: 'system',
    reply: 'Unable to cancel order.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'order_return_requested',
    step: 'system',
    reply: 'Return requested for order {{orderId}}. Our team will contact you within 24hrs.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'error_return_order',
    step: 'system',
    reply: 'Unable to process return request.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'appointment_invalid_datetime',
    step: 'system',
    reply: 'Please provide a valid future appointment date and time. Example: tomorrow 5pm or 2026-05-20 10:00.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'appointment_past_not_allowed',
    step: 'system',
    reply: 'Appointments must be scheduled for a future date and time. Please choose a later date.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'appointment_booked_success',
    step: 'system',
    reply: 'Appointment booked for {{date}} at {{time}}.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'feedback_existing_query',
    step: 'system',
    reply: 'Your query {{queryId}} is under review. Our team will rectify it within 24hrs.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'feedback_new_query',
    step: 'system',
    reply: 'Thanks for your message. Our team will rectify it within 24hrs. Your query ID is {{queryId}}.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'support_invalid_order_id',
    step: 'system',
    reply: 'Invalid order ID. Please provide a valid order ID for support.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'support_order_not_found',
    step: 'system',
    reply: 'No order found with that ID. Please check and try again.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'support_order_found',
    step: 'system',
    reply: 'Order {{orderId}} found. Please share your feedback and mention the product name ({{productName}}).',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'support_feedback_required',
    step: 'system',
    reply: 'Please enter your feedback so we can help you.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'support_feedback_thanks',
    step: 'system',
    reply: 'Thanks for your feedback on {{productName}}. Support request ID: {{ticketId}}. Our team will review and get back to you shortly.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'invalid_option',
    step: 'system',
    reply: 'Invalid option. Type "menu" to see all options.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'invalid_option_generic',
    step: 'system',
    reply: 'Invalid option. Please try again.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'address_invalid',
    step: 'system',
    reply: 'Please enter a complete delivery address.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'quantity_invalid',
    step: 'system',
    reply: 'Please enter a valid quantity (1 or more).',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'payment_method_invalid',
    step: 'system',
    reply: 'Please choose a valid payment method: online payment or cash on delivery.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'payment_online_only',
    step: 'system',
    reply: 'Orders above Rs 10,000 require online payment only. Please choose online payment.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'cancel_order_id_invalid',
    step: 'system',
    reply: 'Please enter a valid order ID to cancel.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'cancel_reason_invalid',
    step: 'system',
    reply: 'Please provide a valid cancellation reason.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'return_order_id_invalid',
    step: 'system',
    reply: 'Please enter a valid order ID for return.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'return_reason_invalid',
    step: 'system',
    reply: 'Please provide a valid return reason.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'ask_return_order_id',
    step: 'system',
    reply: 'Please enter your order ID to request a return.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'ask_cancel_order_id',
    step: 'system',
    reply: 'Please enter your order ID to cancel the order.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'ask_feedback_query',
    step: 'system',
    reply: 'Please enter your existing query ID or type Continue to create a new query.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'ask_support_order_id',
    step: 'system',
    reply: 'Please provide your order ID so we can assist you with support.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'cancel_after_delivered_not_allowed',
    step: 'system',
    reply: 'Order is already delivered. You can only return the product.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'return_only_delivered',
    step: 'system',
    reply: 'Only delivered orders can be returned.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'ask_refund_upi',
    step: 'system',
    reply: 'Please share your UPI ID for refund.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'refund_upi_invalid',
    step: 'system',
    reply: 'Please enter a valid UPI ID (example: name@bank).',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'confirm_existing_upi',
    step: 'system',
    reply: 'We found your UPI ID: {{upiId}}. Reply Yes to use this, or reply New to share a different UPI ID.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'refund_credit_24h',
    step: 'system',
    reply: 'Amount will credit within 24hrs.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'cancel_only_own_order',
    step: 'system',
    reply: 'You can cancel only your own ordered product.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'return_only_own_order',
    step: 'system',
    reply: 'You can return only your own ordered product.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'payment_summary',
    step: 'system',
    reply: 'Order Summary:\n{{productName}} x {{quantity}}\nMRP: Rs {{mrp}}\nOffer Price: Rs {{offerPrice}}\nDiscount: {{discountPercent}}%\nSubtotal (MRP x Qty): Rs {{subtotalMrp}}\nDiscounted Total: Rs {{discountedSubtotal}}\nCoupon Discount: Rs {{couponDiscount}}\nFinal Price: Rs {{finalPrice}}\n\n{{paymentOptions}}\n\nReply with 1/2 or online/cash.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'payment_summary_error',
    step: 'system',
    reply: 'Unable to prepare payment summary. Please choose product again.',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
  {
    trigger: 'system_error',
    step: 'system',
    reply: 'Something went wrong. Please try again or type "menu".',
    nextStep: 'system',
    action: 'NONE',
    isActive: true,
  },
];

export async function seedChatbotFlows(businessId) {
  for (const flow of SAMPLE_FLOWS) {
    await ChatbotFlow.findOneAndUpdate(
      {
        businessId,
        step: flow.step,
        trigger: flow.trigger,
      },
      {
        $set: {
          ...flow,
          businessId,
        },
      },
      { upsert: true, new: true }
    );
  }
}

export default seedChatbotFlows;
